version: '3.9'

networks:
  wordpress:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress

  # phpmyadmin:
  #   depends_on:
  #     - nginx
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: secret
  #   networks:
  #     - wordpress

  # wp:
  #   build:
  #     context: .
  #     dockerfile: php.dockerfile
  #   container_name: wp
  #   entrypoint: ['wp', '--allow-root']
  #   volumes:
  #     - ./wordpress:/var/www/html:delegated
  #   networks:
  #     - wordpress
